# Generated by Django 5.2.3 on 2025-07-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
