from .NewsList.views import *
from .TagList.views import *
from .TagCreate.views import *
from .CategoryCreate.views import *
from .NewsCreate.views import *
from .CategoryDelete.views import *
from .CategoryList.views import *
from .CommentCreate.views import *
from .CommentDelete.views import *
from .CommentsList.views import *
from .NewsUpdate.views import *
from .TagDelete.views import *
from .NewsDelete.views import *